name: CURSO_DART_DESDE_CERO
description: A simple command-line application.
version: 0.0.1
# homepage: https://www.example.com

enviroment:
  sdk: '^3.0.0'

dependencies:
  #path: ^1.8.3
  random_string: ^2.3.1

dev_dependencies:
  pedantic: ^1.9.0


